version: "3.8"
services:
  nextjs-app:
    build: .
    ports:
      - "8999:8999"
    volumes:
      - ./:/app
    working_dir: /app
    command: npm run dev:port
    environment:
      DATABASE_HOST: "192.168.226.53" # Or host.docker.internal
      DATABASE_PORT: "3306"
      DATABASE_USER: "ehidiamen"
      DATABASE_PASSWORD: "goodhitage@"
      DATABASE_NAME: "school_management"
      CHOKIDAR_USEPOLLING: "true"
      GOOGLE_API_KEY: "AIzaSyAf1KLXN1JJIKjwfrw1DEcmXqYMQaNmW3Q"
      AUTH_GOOGLE_ID: "1001842009566-t41f9v9eqkooe7g51bje199l1ohhsjh2.apps.googleusercontent.com"
      AUTH_GOOGLE_SECRET: "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"
      #AUTH_SECRET="mifKwnHkoC+B1o0dlMiEr60rbCFwCdcdPStsgF+e/14="
      AUTH_SECRET: "qTX9EmAWuJXJ67OJjc1O5HhY6IbjLO8VWoYLuWmiyqk="
      NEXTAUTH_SECRET: "qTX9EmAWuJXJ67OJjc1O5HhY6IbjLO8VWoYLuWmiyqk="
      AUTH_GITHUB_ID: "Ov23liMd3bvIv685aTyN"
      AUTH_GITHUB_SECRET: "3c0f271dc2e1e23a3dfff7efcc1a77fd7e5e5aa7"
      DATABASE_URL: "mysql://ehidiamen:goodhitage@host.docker.internal:3306/school_management"
      EMAIL_SERVER_USER: "no_reply@echang.com.ng"
      EMAIL_SERVER_PASSWORD: "no_replyageat89#"
      EMAIL_SERVER_HOST: "echang.com.ng"
      EMAIL_SERVER_PORT: 465
      EMAIL_FROM: "no_reply@echang.com.ng"
      SIGNIN_ERROR_URL: "/err_page"
      NEXT_URL: "http://localhost:8999"
      NEXTAUTH_URL: "http://localhost:8999"
      AUTH_TRUST_HOST: "localhost:8999"